// Regional Latin America benchmarks (approximate values, mid-2025 / early 2026 references)
// Sources: BCRA, BCB, Banxico, BCCh, BCRP, BCU, Fed, IMF WEO, Trading Economics
// Values are rounded and intended for interpretive comparison, not decisional accuracy.

export const REGIONAL = {
  mdr: {
    unit: 'x',
    lower_is_better: true,
    scale_hint: 'log',
    series: [
      { country: 'Argentina',   sub: 'Milei live',         value: 0.04, highlight: true },
      { country: 'Argentina',   sub: 'Fernandez peak 23Q4',value: 2.50, historical: true },
      { country: 'Argentina',   sub: 'Macri peak 18Q3',    value: 1.16, historical: true },
      { country: 'Chile',       sub: 'BCCh sterilization', value: 0.15 },
      { country: 'Brazil',      sub: 'Operacoes compromis.',value: 0.28 },
      { country: 'Mexico',      sub: 'Banxico BREM',       value: 0.09 },
      { country: 'Peru',        sub: 'BCRP CDR',           value: 0.05 },
      { country: 'Uruguay',     sub: 'BCU LRM',            value: 0.20 },
    ],
    insight: 'Under Fernandez, Argentina ran a monetary overhang 10-50x higher than any disciplined LatAm peer. Milei has moved below Peru\'s baseline via LEFI absorption.',
  },
  cantillon: {
    unit: '%',
    lower_is_better: true,
    series: [
      { country: 'Argentina',   sub: 'Kirchner era',       value: 250, historical: true },
      { country: 'Argentina',   sub: 'Milei live',         value: 58, highlight: true },
      { country: 'Venezuela',   sub: '2015-24 hyperinf.',  value: 380 },
      { country: 'Turkey',      sub: '2020-24 crisis',     value: 120 },
      { country: 'Brazil',      sub: '2020-24 avg',        value: 34 },
      { country: 'Chile',       sub: 'IPSA vs wages',      value: 22 },
      { country: 'Mexico',      sub: 'BMV vs wages',       value: 41 },
      { country: 'USA',         sub: 'S&P vs wages',       value: 68 },
    ],
    insight: 'The Cantillon gap correlates with monetary chaos. Only hyperinflating economies (VZ, TR) exceed Argentina Kirchner-era wealth transfer. Milei\'s +58% is now closer to US S&P dynamics than LatAm norm.',
  },
  fcr: {
    unit: '%',
    lower_is_better: true,
    series: [
      { country: 'Venezuela',   sub: 'PDVSA + tariff subs.',value: 42 },
      { country: 'Argentina',   sub: 'Kirchner era',       value: 19, historical: true },
      { country: 'Argentina',   sub: 'Fernandez',          value: 14, historical: true },
      { country: 'Ecuador',     sub: 'fuel subs.',         value: 12 },
      { country: 'Argentina',   sub: 'Milei live',         value: 6.2, highlight: true },
      { country: 'Brazil',      sub: 'Bolsa Fam. + Auxilio',value: 8 },
      { country: 'Mexico',      sub: 'CFE + Pemex',        value: 6 },
      { country: 'Chile',       sub: 'targeted subs.',     value: 3 },
      { country: 'Uruguay',     sub: 'UTE + ANCAP',        value: 4 },
    ],
    insight: 'Latin America ranges 3-12% typical. Argentina Kirchner (19%) and Venezuela (42%) sit in "sector capture state" territory. Milei has moved Argentina into the disciplined-Latin cluster.',
  },
  reservas: {
    unit: 'B USD',
    lower_is_better: false,
    normalize_to: 'pct_gdp',
    series: [
      { country: 'Argentina',   sub: '~7% of GDP',         value: 50, highlight: true },
      { country: 'Brazil',      sub: '~15% of GDP',        value: 353 },
      { country: 'Mexico',      sub: '~14% of GDP',        value: 230 },
      { country: 'Peru',        sub: '~28% of GDP',        value: 78 },
      { country: 'Chile',       sub: '~14% of GDP',        value: 47 },
      { country: 'Colombia',    sub: '~15% of GDP',        value: 62 },
      { country: 'Uruguay',     sub: '~23% of GDP',        value: 18 },
    ],
    insight: 'Argentina holds the lowest reserves-to-GDP ratio in the region. Peru and Uruguay run 3-4x more insurance relative to their economy size.',
  },
  usd_ars: {
    unit: '% depreciation vs USD (5y)',
    lower_is_better: true,
    series: [
      { country: 'Argentina',   sub: 'ARS 60 to 1500',     value: -96, highlight: true },
      { country: 'Turkey',      sub: 'reference case',     value: -85 },
      { country: 'Colombia',    sub: 'COP',                value: -35 },
      { country: 'Chile',       sub: 'CLP',                value: -30 },
      { country: 'Brazil',      sub: 'BRL',                value: -25 },
      { country: 'Peru',        sub: 'PEN',                value: -12 },
      { country: 'Mexico',      sub: 'MXN (super peso)',   value: -5 },
    ],
    insight: 'The Argentine peso is the second-worst-performing currency vs USD in the last 5 years, behind only Turkey. Mexican peso outperformed via near-shoring flows and Banxico discipline.',
  },
  base_mon: {
    unit: '% of GDP',
    lower_is_better: null,
    series: [
      { country: 'USA',         sub: 'post-QE',            value: 24 },
      { country: 'Chile',       sub: 'BCCh',               value: 6 },
      { country: 'Peru',        sub: 'BCRP',               value: 6 },
      { country: 'Argentina',   sub: 'BCRA live',          value: 5, highlight: true },
      { country: 'Brazil',      sub: 'BCB',                value: 4 },
      { country: 'Mexico',      sub: 'Banxico',            value: 4 },
    ],
    insight: 'Argentina\'s base money is small relative to GDP because hyperinflation destroyed peso demand. Argentines hold USD as savings instead.',
  },
  m2: {
    unit: '% of GDP',
    lower_is_better: null,
    series: [
      { country: 'Chile',       sub: 'high monetization', value: 55 },
      { country: 'Mexico',      sub: 'BM',                 value: 35 },
      { country: 'Brazil',      sub: 'BCB',                value: 30 },
      { country: 'Peru',        sub: 'BCRP',               value: 27 },
      { country: 'Uruguay',     sub: 'BCU',                value: 22 },
      { country: 'Argentina',   sub: 'live estimate',      value: 12, highlight: true },
    ],
    insight: 'Argentina has the LEAST monetized economy in the region. Dollarization behavior means citizens save in USD, keeping M2/GDP structurally low.',
  },
  ipc_yoy: {
    unit: '%',
    lower_is_better: true,
    scale_hint: 'log',
    series: [
      { country: 'Venezuela',   sub: '2024 estimate',      value: 100 },
      { country: 'Argentina',   sub: 'BCRA live',          value: 33, highlight: true },
      { country: 'Argentina',   sub: 'Fernandez peak',     value: 289, historical: true },
      { country: 'Colombia',    sub: 'DANE',               value: 6 },
      { country: 'Uruguay',     sub: 'INE',                value: 5 },
      { country: 'Mexico',      sub: 'INEGI',              value: 4.5 },
      { country: 'Brazil',      sub: 'IPCA',               value: 4 },
      { country: 'Chile',       sub: 'INE',                value: 4 },
      { country: 'Peru',        sub: 'INEI',               value: 2 },
    ],
    insight: 'Argentina inflation dropped 89% in absolute terms from Fernandez peak (289%) but remains 5-15x higher than regional peers. Peru is the LatAm inflation anchor.',
  },
  ipc_mom: {
    unit: '%',
    lower_is_better: true,
    series: [
      { country: 'Argentina',   sub: 'BCRA live',          value: 1.9, highlight: true },
      { country: 'Turkey',      sub: 'reference',          value: 3.2 },
      { country: 'Colombia',    sub: 'DANE',               value: 0.55 },
      { country: 'Brazil',      sub: 'IPCA',               value: 0.4 },
      { country: 'Uruguay',     sub: 'INE',                value: 0.45 },
      { country: 'Mexico',      sub: 'INEGI',              value: 0.4 },
      { country: 'Chile',       sub: 'INE',                value: 0.3 },
    ],
    insight: 'Monthly inflation of 1.9% still compounds to ~25% yearly. Regional peers run 0.3-0.6%/month. Argentina needs to reach ~0.5% to converge.',
  },
  badlar: {
    unit: '%',
    lower_is_better: null,
    series: [
      { country: 'Argentina',   sub: 'BADLAR live',        value: 22, highlight: true },
      { country: 'Turkey',      sub: 'reference case',     value: 50 },
      { country: 'Brazil',      sub: 'Selic',              value: 11 },
      { country: 'Mexico',      sub: 'TIIE',               value: 10 },
      { country: 'Colombia',    sub: 'BanRep',             value: 9 },
      { country: 'Uruguay',     sub: 'TPM',                value: 8 },
      { country: 'Chile',       sub: 'TPM',                value: 5 },
      { country: 'Peru',        sub: 'BCRP',               value: 5 },
    ],
    insight: 'Argentine wholesale rates remain 2-4x above disciplined peers. As inflation converges, expect BADLAR to compress toward Brazil / Mexico range.',
  },
  mdr_live: {
    unit: 'x',
    lower_is_better: true,
    series: [
      { country: 'Argentina',   sub: 'live',               value: 0.04, highlight: true },
      { country: 'Argentina',   sub: 'Fernandez peak',     value: 2.50, historical: true },
      { country: 'Chile',       sub: 'BCCh',               value: 0.15 },
      { country: 'Brazil',      sub: 'BCB',                value: 0.28 },
      { country: 'Peru',        sub: 'BCRP',               value: 0.05 },
    ],
    insight: 'Real-time MDR from BCRA feed. Argentina now below Peru discipline vs 50x above it under Fernandez.',
  },
  sector_capture: {
    unit: '% (capture ratio)',
    lower_is_better: null,
    series: [
      { country: 'Argentina Agriculture', sub: 'Kirchner retenciones',  value: -42, historical: true },
      { country: 'Argentina Agriculture', sub: 'live',                  value: -18, highlight: true },
      { country: 'Brazil Agriculture',    sub: 'Plano Safra (net)',     value: 3 },
      { country: 'Chile Agriculture',     sub: 'no ret., mild subs',    value: 2 },
      { country: 'Uruguay Agriculture',   sub: 'no ret.',               value: 0 },
      { country: 'USA Agriculture',       sub: 'Farm Bill subsidies',   value: 12 },
      { country: 'EU Agriculture',        sub: 'CAP subsidies',         value: 22 },
    ],
    insight: 'Argentina is one of the very few nations that structurally EXTRACTS from its agricultural sector via export duties (retenciones). Most peers subsidize the sector.',
  },
  extraction: {
    unit: '% of GDP',
    lower_is_better: null,
    series: [
      { country: 'France',      sub: 'high-tax OECD',     value: 46 },
      { country: 'Brazil',      sub: 'total tax burden',  value: 33 },
      { country: 'Argentina',   sub: 'traditional + infl.', value: 28, highlight: true },
      { country: 'Argentina',   sub: 'Kirchner peak',     value: 33, historical: true },
      { country: 'Uruguay',     sub: 'DGI',               value: 27 },
      { country: 'Chile',       sub: 'SII',               value: 21 },
      { country: 'Colombia',    sub: 'DIAN',              value: 20 },
      { country: 'Peru',        sub: 'SUNAT',             value: 17 },
      { country: 'Mexico',      sub: 'SAT',               value: 17 },
    ],
    insight: 'Total Argentine extraction (traditional + inflation tax) puts it in OECD-tax-burden territory despite much lower institutional quality. Peru and Mexico run near half the extraction.',
  },
  destination: {
    unit: '% of GDP (subs + transfers)',
    lower_is_better: null,
    series: [
      { country: 'Argentina',   sub: 'Kirchner peak',     value: 16.5, historical: true },
      { country: 'Argentina',   sub: 'Fernandez',         value: 13.9, historical: true },
      { country: 'France',      sub: 'CAP + energy',      value: 11 },
      { country: 'Brazil',      sub: 'Bolsa + energy',    value: 10 },
      { country: 'Argentina',   sub: 'Milei live',        value: 5.2, highlight: true },
      { country: 'Chile',       sub: 'targeted only',     value: 4 },
      { country: 'Mexico',      sub: 'Pemex + CFE',       value: 6 },
      { country: 'Uruguay',     sub: 'UTE + ANCAP',       value: 5 },
    ],
    insight: 'Sector-targeted transfers under Milei are now inside the regional norm (4-6%). Kirchner peak of 16.5% was closer to France\'s welfare-state levels than to any LatAm peer.',
  },
  real_term_toggle: {
    unit: 'Multiplier',
    lower_is_better: null,
    series: [
      { country: 'Nominal ARS 2003',  sub: 'peso valued 500x current', value: 500, historical: true },
      { country: 'Nominal ARS 2015',  sub: '~150x',                    value: 150, historical: true },
      { country: 'Nominal ARS 2020',  sub: '~10x',                     value: 10, historical: true },
      { country: 'Nominal ARS 2026',  sub: 'baseline',                 value: 1, highlight: true },
    ],
    insight: 'Comparing raw ARS across decades is meaningless due to devaluation. Toggle converts to USD real-2024 basis (~1200 ARS/USD) so 2003 vs 2026 magnitudes are directly comparable.',
  },
}
